services:
    gedmo.listener.sluggable:
        class: Gedmo\Sluggable\SluggableListener
        tags:
            - { name: doctrine.event_subscriber, connection: default }
        calls:
            - [ setAnnotationReader, [ '@annotation_reader' ] ]
    poke.filenamer:
        class: PokeBundle\FileNamer\FileNamer
        tags:
            - { name: namer }
    poke.comment_manager:
        class: PokeBundle\Manager\CommentManager
        arguments: ["@doctrine.orm.entity_manager"]
    poke.shiny_manager:
        class: PokeBundle\Manager\ShinyManager
        arguments: ["@doctrine.orm.entity_manager"]
    poke.pokemon_manager:
        class: PokeBundle\Manager\PokemonManager
        arguments: ["@doctrine.orm.entity_manager"]
    poke.experience_manager:
        class: PokeBundle\Service\Experience
        arguments: ['@doctrine.orm.entity_manager']
    poke.follower_manager:
        class: PokeBundle\Service\Follower
        arguments: ['@doctrine.orm.entity_manager']
    poke.reporter_manager:
        class: PokeBundle\Service\Reporter
        arguments: ['@doctrine.orm.entity_manager']