<?php

namespace PokeBundle\Repository;

/**
 * ShinyRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ShinyRepository extends \Doctrine\ORM\EntityRepository
{
}
