<?php

namespace PokeBundle\Repository;

/**
 * ShinyRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ShinyRepository extends \Doctrine\ORM\EntityRepository
{

	public function getLastShinies($limit){
		$query = $this 	->createQueryBuilder('s')
						->orderBy('s.dateCreation', 'DESC')
						->setMaxResults($limit);

        return  $query  ->getQuery()
                        ->getResult();
	}
	public function getShinyByPokemonAndHunter($hunter,$pokemon){
		$query = $this 	->createQueryBuilder('s')
						->leftJoin('s.pokemon', 'p')
						->where('p.slug = :pokemon')
						->andWhere('s.user = :user')
						->setParameter('pokemon', $pokemon)
						->setParameter('user', $hunter);

        return  $query  ->getQuery()
                        ->getOneOrNullResult();
	}
}
